Better user notification
configcat/trello-powerup pull request #50
Opened 2023-10-20 14:51 UTC by novalisdenahi

### Describe the purpose of your pull request

- Fix security issues
- Fix text color on dark Trello theme
- Feature flag settings component handles auth and other errors better and notifies the user properly

### Requirement checklist (only if applicable)

- [ ] I have covered the applied changes with automated tests.
- [ ] I have executed the full automated test set against my changes.
- [ ] I have validated my changes against all supported platform versions.
- [ ] I have read and accepted the [contribution agreement](https://github.com/configcat/legal/blob/main/contribution-agreement.md).

2023-10-20 14:53 UTC, laliconfigcat requested changes

2023-10-20 14:53 UTC, laliconfigcat commented on src/app/feature-flags-settings/feature-flags-settings.component.ts
> +        if (error.status == 401) {
```suggestion
        if (error?.status === 401) {
```

2023-10-24 07:24 UTC, laliconfigcat approved these changes

2023-10-24 16:22 UTC, sigewuzhere requested changes

2023-10-24 16:22 UTC, sigewuzhere commented on src/app/feature-flags-settings/feature-flags-settings.component.html
> +            <p>Please try again later or for more inforamtion check the console logs.</p>
```suggestion
            <p>You can try again later or check the console log for more information.</p>
```

B version:

You can try again later, check the console log for more information or contact us [link].

Not sure if this is applicable here.

2023-10-24 16:22 UTC, sigewuzhere commented on src/app/services/trello-service.ts
> +                message: 'Authorization failed! Please try to login again.',
```suggestion
                message: 'Authorization failed. Please try again or contact us [link].',
```

2023-10-25 13:24 UTC, novalisdenahi commented on src/app/services/trello-service.ts
> +                message: 'Authorization failed! Please try to login again.',
@sigewuzhere I wouldn't put a link into the alert box. If the user is slow to check it, it is really frustrating when it closes and you can't click it.  Also, I think the "try to login in again" is more valid in this case. This alert will come up not after you fail your login, it will be shown after something happened with your credential and we logged you out.

2023-10-25 13:26 UTC, novalisdenahi commented on src/app/feature-flags-settings/feature-flags-settings.component.html
> +            <p>Please try again later or for more inforamtion check the console logs.</p>
@sigewuzhere The link can work here. Good idea! The link can point to https://configcat.com/support/. What do you think?

2023-10-26 09:08 UTC, sigewuzhere commented on src/app/services/trello-service.ts
> +                message: 'Authorization failed! Please try to login again.',
Okay I see, in this case I'd recommend something like this:

`Authorization failed. Please try to login again or contact us.`

2023-11-03 08:37 UTC, merged